# Generated by Django 5.2.8 on 2025-11-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Електронна пошта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата підписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна підписка')),
            ],
            options={
                'verbose_name': 'Підписник',
                'verbose_name_plural': 'Підписники',
                'ordering': ['-created'],
            },
        ),
    ]
